# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InstaUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname_user', models.CharField(max_length=100)),
                ('email_user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('image_id', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('publicated_at', models.DateTimeField()),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.Images')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.InstaUser')),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.InstaUser'),
        ),
        migrations.AddField(
            model_name='comments',
            name='publication_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.Publications'),
        ),
        migrations.AddField(
            model_name='comments',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.InstaUser'),
        ),
    ]
