# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
