# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='image_id',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
