# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_auto_20171105_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='nickname_user',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
