# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_auto_20171105_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='image_id',
            field=models.ImageField(blank=True, upload_to='insta/photos'),
        ),
    ]
