# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('image_id', models.ImageField(upload_to='insta/photos')),
            ],
        ),
        migrations.CreateModel(
            name='InstaUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname_user', models.CharField(max_length=100, unique=True)),
                ('email_user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('image_id', models.ImageField(blank=True, upload_to='insta/photos')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.Images')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.InstaUser')),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.InstaUser'),
        ),
        migrations.AddField(
            model_name='comments',
            name='publication_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.Images'),
        ),
        migrations.AddField(
            model_name='comments',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.InstaUser'),
        ),
    ]
