# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('follow_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_out', to='insta.InstaUser')),
                ('man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_im', to='insta.InstaUser')),
            ],
        ),
    ]
